name: Bug Report
description: Report a problem in Rofi
labels: [bug]
title: "[BUG] "
body:

  - type: markdown
    attributes:
      value: |
        First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! This is not optional for any report. People must be able to understand the full context of the report when reading it, at any time.

        If you feel like you “it is simple and requires no explanation”, please consider you’re wrong and still fill the full report. Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
        If you ask a question, enter dummy information in required fields to get passed the checks or in general completely ignore the guidelines, the issue will be closed and locked as spam.

        If you are unsure, please use the [discussion](https://github.com/davatorium/rofi/discussions) forum first. It is easy to upgrade a question to an issue in github.

        If you report problems with speed in rofi, please attach a [timing trace](https://github.com/davatorium/rofi/blob/next/doc/rofi-debugging.5.markdown#timing-traces).

        **Please do not submit reports related to wayland, see [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more information.**

  - type: input
    attributes:
      label: "Rofi version (rofi -v)"
      placeholder: "Version: 1.6.0"
    validations:
      required: true
  - type: input
    attributes:
      label: "Configuration"
      description: "Please use https://gist.github.com and include output of `rofi -dump-config` and `rofi -dump-theme`."
      placeholder: "Gist URL"
    validations:
      required: true
  - type: input
    attributes:
      label: "Launch command"
      placeholder: "rofi -show drun"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Step to reproduce"
      placeholder: |
        * Step 1
        * Step 2
        * ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe the behavior you expect. May include logs, images, or videos."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behavior"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional information"
    validations:
      required: false


