Document: cgdb
Title: Debian cgdb Manual
Author: <insert document author here>
Abstract: This manual describes what cgdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cgdb/cgdb.sgml.gz

Format: postscript
Files: /usr/share/doc/cgdb/cgdb.ps.gz

Format: text
Files: /usr/share/doc/cgdb/cgdb.text.gz

Format: HTML
Index: /usr/share/doc/cgdb/html/index.html
Files: /usr/share/doc/cgdb/html/*.html
