Document: iverilog
Title: Debian iverilog Manual
Author: <insert document author here>
Abstract: This manual describes what iverilog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iverilog/iverilog.sgml.gz

Format: postscript
Files: /usr/share/doc/iverilog/iverilog.ps.gz

Format: text
Files: /usr/share/doc/iverilog/iverilog.text.gz

Format: HTML
Index: /usr/share/doc/iverilog/html/index.html
Files: /usr/share/doc/iverilog/html/*.html
