Document: rofi
Title: Debian rofi Manual
Author: <insert document author here>
Abstract: This manual describes what rofi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rofi/rofi.sgml.gz

Format: postscript
Files: /usr/share/doc/rofi/rofi.ps.gz

Format: text
Files: /usr/share/doc/rofi/rofi.text.gz

Format: HTML
Index: /usr/share/doc/rofi/html/index.html
Files: /usr/share/doc/rofi/html/*.html
